<option value="School">School </option>
<option value="Heat Transfer">Heat Transfer</option>
<option value="Fluid Mechanics">Fluid Mechanics</option>
<option value="Thermal">Thermal</option>
<option value="Database Management System">Database Management System</option>
<option value="Compiler">Compilers</option>
<option value="Software Engineering">Software Engineering</option>
<option value="Mathamatics">Mathamatics</option>
<option value="Science">Science</option>
<option value="Operating System">Operating System</option>
<option value="Mechanical">Mechanical</option>
<option value="BioTechnology">BioTechnology</option>
<option value="Chemistry">Chemistry</option>
<option value="Logic Designing">Logic Designing</option>
<option value="Medicals">Medicals</option>
<option value="Electrical">Electrical</option>
<option value="English">English</option>
<option value="Physics">Physics</option>
<option value="Commerce">Commerce</option>
<option value="Fan-Fiction">Fan-Fiction</option>
<option value="Comics">Comics</option>
